export const DSTV = [
  {
    variation_code: "dstv-padi",
    name: "DStv Padi N4,400",
    variation_amount: "4400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-yanga",
    name: "DStv Yanga N6,000",
    variation_amount: "6000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-confam",
    name: "Dstv Confam N11,000",
    variation_amount: "11000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv79",
    name: "DStv  Compact N19,000",
    variation_amount: "19000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv3",
    name: "DStv Premium N44,500",
    variation_amount: "44500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv7",
    name: "DStv Compact Plus N30,000",
    variation_amount: "30000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv9",
    name: "DStv Premium-French N69,000",
    variation_amount: "69000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv10",
    name: "DStv Premium-Asia N50,500",
    variation_amount: "50500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "confam-extra",
    name: "DStv Confam + ExtraView N17,000",
    variation_amount: "17000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "yanga-extra",
    name: "DStv Yanga + ExtraView N12,000",
    variation_amount: "12000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "padi-extra",
    name: "DStv Padi + ExtraView N10,400",
    variation_amount: "10400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv30",
    name: "DStv Compact + Extra View N25,000",
    variation_amount: "25000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "com-frenchtouch",
    name: "DStv Compact + French Touch N26,000",
    variation_amount: "26000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv33",
    name: "DStv Premium + Extra View N50,500",
    variation_amount: "50500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "com-frenchtouch-extra",
    name: "DStv Compact + French Touch + ExtraView N32,000",
    variation_amount: "32000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv43",
    name: "DStv Compact Plus + French Plus N54,500",
    variation_amount: "54500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "complus-frenchtouch",
    name: "DStv Compact Plus + French Touch N37,000",
    variation_amount: "37000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv45",
    name: "DStv Compact Plus + Extra View N36,000",
    variation_amount: "36000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "complus-french-extraview",
    name: "DStv Compact Plus + FrenchPlus + Extra View N60,500",
    variation_amount: "60500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv47",
    name: "DStv Compact + French Plus N43,500",
    variation_amount: "43500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv62",
    name: "DStv Premium + French + Extra View N75,000",
    variation_amount: "75000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "frenchplus-addon",
    name: "DStv French Plus Add-on N24,500",
    variation_amount: "24500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-greatwall",
    name: "DStv Great Wall Standalone Bouquet N3,800",
    variation_amount: "3800.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "frenchtouch-addon",
    name: "DStv French Touch Add-on N7,000",
    variation_amount: "7000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "extraview-access",
    name: "ExtraView Access N6,000",
    variation_amount: "6000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-yanga-showmax",
    name: "DStv Yanga + Showmax N7,750",
    variation_amount: "7750.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-greatwall-showmax",
    name: "DStv Great Wall Standalone Bouquet + Showmax N7,300",
    variation_amount: "7300.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-compact-plus-showmax",
    name: "DStv Compact Plus + Showmax N31,750",
    variation_amount: "31750.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-confam-showmax",
    name: "Dstv Confam + Showmax N12,750",
    variation_amount: "12750.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-compact-showmax",
    name: "DStv  Compact + Showmax N20,750",
    variation_amount: "20750.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-padi-showmax",
    name: "DStv Padi + Showmax N7,900",
    variation_amount: "7900.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-asia-showmax",
    name: "DStv Asia + Showmax N18,400",
    variation_amount: "18400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-premium-french-showmax",
    name: "DStv Premium + French + Showmax N69,000",
    variation_amount: "69000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-premium-showmax",
    name: "DStv Premium + Showmax N44,500",
    variation_amount: "44500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-indian",
    name: "DStv Indian N14,900",
    variation_amount: "14900.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-premium-indian",
    name: "DStv Premium East Africa and Indian N16530",
    variation_amount: "16530.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-fta-plus",
    name: "DStv FTA Plus N1,600",
    variation_amount: "1600.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-premium-hd",
    name: "DStv PREMIUM HD N39,000",
    variation_amount: "39000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-access-1",
    name: "DStv Access N2000",
    variation_amount: "2000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-family-1",
    name: "DStv Family",
    variation_amount: "4000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-indian-add-on",
    name: "DStv India Add-on N14,900",
    variation_amount: "14900.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-mobile-1",
    name: "DSTV MOBILE N790",
    variation_amount: "790.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-movie-bundle-add-on",
    name: "DStv Movie Bundle Add-on N3500",
    variation_amount: "3500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-pvr-access",
    name: "DStv PVR Access Service N4000",
    variation_amount: "4000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "dstv-premium-wafr-showmax",
    name: "DStv Premium W/Afr + Showmax N50,500",
    variation_amount: "50500.00",
    fixedPrice: "Yes",
  },
];

export const GOTV = [
  {
    variation_code: "gotv-max",
    name: "GOtv Max N8,500",
    variation_amount: "8500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "gotv-jolli",
    name: "GOtv Jolli N5,800",
    variation_amount: "5800.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "gotv-jinja",
    name: "GOtv Jinja N3,900",
    variation_amount: "3900.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "gotv-smallie",
    name: "GOtv Smallie - monthly N1900",
    variation_amount: "1900.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "gotv-smallie-3months",
    name: "GOtv Smallie - quarterly N5,100",
    variation_amount: "5100.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "gotv-smallie-1year",
    name: "GOtv Smallie - yearly N15,000",
    variation_amount: "15000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "gotv-supa",
    name: "GOtv Supa - monthly N11,400",
    variation_amount: "11400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "gotv-supa-plus",
    name: "GOtv Supa Plus - monthly N16,800",
    variation_amount: "16800.00",
    fixedPrice: "Yes",
  },
];

export const STARTIMES = [
  {
    variation_code: "nova",
    name: "Nova (Dish) - 2100 Naira - 1 Month",
    variation_amount: "2100.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "basic",
    name: "Basic (Antenna) - 4,000 Naira - 1 Month",
    variation_amount: "4000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "smart",
    name: "Basic (Dish) - 5,100 Naira - 1 Month",
    variation_amount: "5100.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "classic",
    name: "Classic (Antenna) - 6000 Naira - 1 Month",
    variation_amount: "6000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "super",
    name: "Super (Dish) - 9,800 Naira - 1 Month",
    variation_amount: "9800.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "nova-weekly",
    name: "Nova (Antenna) - 700 Naira - 1 Week",
    variation_amount: "700.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "basic-weekly",
    name: "Basic (Antenna) - 1400 Naira - 1 Week",
    variation_amount: "1400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "smart-weekly",
    name: "Basic (Dish) - 1,700 Naira - 1 Week",
    variation_amount: "1700.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "classic-weekly",
    name: "Classic (Antenna) - 2000 Naira - 1 Week",
    variation_amount: "2000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "super-weekly",
    name: "Super (Dish) - 3,300 Naira - 1 Week",
    variation_amount: "3300.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "uni-1",
    name: "Chinese (Dish) - 21,000 Naira - 1 month",
    variation_amount: "21000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "uni-2",
    name: "Nova (Antenna) - 2,100 Naira - 1 Month",
    variation_amount: "2100.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "special-weekly",
    name: "Classic (Dish) - 2300 Naira - 1 Week",
    variation_amount: "2300.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "special-monthly",
    name: "Classic (Dish) - 7400 Naira - 1 Month",
    variation_amount: "7400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "nova-dish-weekly",
    name: "Nova (Dish) - 700 Naira - 1 Week",
    variation_amount: "700.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "super-antenna-weekly",
    name: "Super (Antenna) - 3,200 Naira - 1 Week",
    variation_amount: "3200.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "super-antenna-monthly",
    name: "Super (Antenna) - 9,500 Naira - 1 Month",
    variation_amount: "9500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "classic-weekly-dish",
    name: "Classic (Dish) - 2500 Naira - 1 Week",
    variation_amount: "2500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "global-monthly-dish",
    name: "Global (Dish) - 21000 Naira - 1 Month",
    variation_amount: "21000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "global-weekly-dish",
    name: "Global (Dish) - 7000 Naira - 1Week",
    variation_amount: "7000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "shs-weekly-2800",
    name: "Startimes SHS - 2,800 Naira - Weekly",
    variation_amount: "2800.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "shs-weekly-4620",
    name: "Startimes SHS - 4,620 Naira - Weekly",
    variation_amount: "4620.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "shs-weekly-4900",
    name: "Startimes SHS - 4,900 Naira - Weekly",
    variation_amount: "4900.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "shs-weekly-9100",
    name: "Startimes SHS - 9,100 Naira - Weekly",
    variation_amount: "9100.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "shs-monthly-12000",
    name: "Startimes SHS - 12,000 Naira - Monthly",
    variation_amount: "12000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "shs-monthly-19800",
    name: "Startimes SHS - 19,800 Naira - Monthly",
    variation_amount: "19800.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "shs-monthly-21000",
    name: "Startimes SHS - 21,000 Naira - Monthly",
    variation_amount: "21000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "shs-monthly-39000",
    name: "Startimes SHS - 39,000 Naira - Monthly",
    variation_amount: "39000.00",
    fixedPrice: "Yes",
  },
];

export const SHOWMAX = [
  {
    variation_code: "full",
    name: "Full - N3,500",
    variation_amount: "3500.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "mobile_only",
    name: "Mobile Only - N1,600",
    variation_amount: "1600.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "full_sports_mobile_only",
    name: "Full Sports Mobile Only - N5,400",
    variation_amount: "5400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "sports_mobile_only",
    name: "Sports Mobile Only - N4,000",
    variation_amount: "4000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "full_3",
    name: "Full - N8,400 - 3 Months",
    variation_amount: "8400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "mobile_only_3",
    name: "Mobile Only - N3,800 - 3 Months",
    variation_amount: "3800.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "sports_mobile_only_3",
    name: "Sports Mobile Only - N12,000 - 3 Months",
    variation_amount: "12000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "sports-only-1",
    name: "Sports Only - N3,200",
    variation_amount: "3200.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "sports-only-3",
    name: "Sports Only 3 months - N9,600",
    variation_amount: "9600.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "full-sports-mobile-only-3",
    name: "Full Sports Mobile Only - 3 months - N16,200",
    variation_amount: "16200.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "mobile-only-6",
    name: "Mobile Only - N6,700 - 6 Months",
    variation_amount: "6700.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "full-only-6",
    name: "Full - 6 months - 14,700",
    variation_amount: "14700.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "full-sports-mobile-only-6",
    name: "Full Sports Mobile Only - 6 months - N32,400",
    variation_amount: "32400.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "sports-mobile-only-6",
    name: "Sports Mobile Only - 6 months - N24,000",
    variation_amount: "24000.00",
    fixedPrice: "Yes",
  },
  {
    variation_code: "sports-only-6",
    name: "Sports Only - 6 months - N18,200",
    variation_amount: "18200.00",
    fixedPrice: "Yes",
  },
];
