export const MTN = {
  planTypes: [
    { value: "daily", label: "Daily" },
    { value: "weekly", label: "Weekly" },
    { value: "monthly", label: "Monthly" },
    { value: "xtra-data", label: "Xtradata" },
  ],
  dataPlans: [
    {
      variation_code: "mtn-10mb-100",
      name: "110MB Daily Plan (1 Day) - N100",
      variation_amount: "100.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-230mb-200",
      name: "230MB Daily Plan (1 Day) - N200",
      variation_amount: "200.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-1500mb-1000",
      name: "1.5GB Weekly Plan (7 Days) - N1,000",
      variation_amount: "1000.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-5.5gb-3500",
      name: "7GB Monthly Plan - N3,500",
      variation_amount: "3500.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-3.5gb-1500",
      name: "3.5GB Weekly Plan (7 Days) - N1,500",
      variation_amount: "1500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-data-6500",
      name: "16.5GB Monthly Plan",
      variation_amount: "6500.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-20gb-7500",
      name: "20GB Monthly Plan",
      variation_amount: "7500.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-25gb-9000",
      name: "25GB Monthly Plan",
      variation_amount: "9000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-32gb-11000",
      name: "36GB Monthly Plan",
      variation_amount: "11000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-75gb-20000",
      name: "75GB Monthly Plan",
      variation_amount: "18000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-2.7gb-2000",
      name: "2.7GB + 2mins + 2GB All Night Streaming + 200MB YouTube Music, Monthly Plan - N2000",
      variation_amount: "2000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-1800mb-1500",
      name: "1.8GB + 6mins + 5 SMS, Weekly plan - N1500",
      variation_amount: "1500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-120gb-24000",
      name: "MTN N24,000 120GB  - 30days",
      variation_amount: "24000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-480gb-90000",
      name: "480GB 3-Month Plan - N90,000",
      variation_amount: "90000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-1gb-350",
      name: "MTN N500 1GB + 1.5mins - 1 day",
      variation_amount: "500.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-1gb-600",
      name: "1GB+5mins Weekly Plan",
      variation_amount: "800.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-xtrabundle-500",
      name: "600MB Xtra Bundle Weekly Data (7 Days) - N500",
      variation_amount: "500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-xtra-1000",
      name: "2GB + 2 Mins Monthly Plan - N1,500",
      variation_amount: "1500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-xtra-10000",
      name: "MTN N11,000 Xtradata",
      variation_amount: "11000.00",
      fixedPrice: "Yes",
      planType: "xtra-data",
    },
    {
      variation_code: "mtn-11gb-5000",
      name: "12.5GB Monthly Plan - N5,500",
      variation_amount: "5500.00",
      fixedPrice: "Yes",
      planType: "monthl",
    },
    {
      variation_code: "mtn-12.5gb-5500",
      name: "12.5GB + 36mins + 15 SMS, Weekly plan - 5500",
      variation_amount: "5500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-2-5gb-900",
      name: "MTN N900 2.5GB - 2 days",
      variation_amount: "900.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-150gb-40000",
      name: "150GB 2-Month Plan",
      variation_amount: "40000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-200gb-50000",
      name: "200GB 2-Month Plan",
      variation_amount: "50000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-11gb-3500",
      name: "MTN N3,500 11GB  - 7 days",
      variation_amount: "3500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-500mb-ex-350",
      name: "500MB Daily Plan (1 Day) - N350",
      variation_amount: "350.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-2-5gb-ex-600",
      name: "1.5GB Daily Plan (2 Days) - N600",
      variation_amount: "600.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-2gb-ex-750",
      name: "2GB Daily Plan (2 Days) - N750",
      variation_amount: "750.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-1500mb-ex-1200",
      name: "2.7GB Xtra Bundle Monthly Plan",
      variation_amount: "3000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-8gb-ex-3000",
      name: "MTN N4,500 10GB + 10mins  - 30 days",
      variation_amount: "4500.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-65gb-ex-16000",
      name: "65GB Monthly Plan (30 Days) - N16,000",
      variation_amount: "16000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-500mb-500",
      name: "500MB + 1GB YouTube (7 Days) - N500",
      variation_amount: "500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-3.2gb-1000",
      name: "MTN N1000 3.2GB - 2 days",
      variation_amount: "1000.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-7gb-3000",
      name: "MTN N2500 6GB - 7 days",
      variation_amount: "2500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-3.5gb-2500",
      name: "MTN N2500 3.5GB +5mins Monthly Plan",
      variation_amount: "2500.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
    {
      variation_code: "mtn-xtra-3500",
      name: "MTN N3500 Xtradata",
      variation_amount: "3500.00",
      fixedPrice: "Yes",
      planType: "xtra-data",
    },
    {
      variation_code: "mtn-hynetflex-14500-30",
      name: "60GB Monthly HyNetFlex Plan - N14,500",
      variation_amount: "14500.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-hynetflex-75000-90",
      name: "450GB 3-Month Broadband Plan - N75,000",
      variation_amount: "75000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-hynetflex-9000-30",
      name: "30GB Monthly Broadband Plan - N9,000",
      variation_amount: "9000.00",
      fixedPrice: "Yes",
      planType: "monthly",
    },
    {
      variation_code: "mtn-2.5-750",
      name: "2.5GB Daily Plan - 750 Naira",
      variation_amount: "750.00",
      fixedPrice: "Yes",
      planType: "daily",
    },
    {
      variation_code: "mtn-20-5000",
      name: "20GB Weekly Plan - 5,000 Naira",
      variation_amount: "5000.00",
      fixedPrice: "Yes",
      planType: "weekly",
    },
  ],
};

export const AIRTEL = {
  planTypes: [
    { value: "daily", label: "Daily" },
    { value: "weekly", label: "Weekly" },
    { value: "monthly", label: "Monthly" },
    { value: "xtra-data", label: "Xtradata" },
  ],
};

export const GLO = {
  planTypes: [
    { value: "daily", label: "Daily" },
    { value: "weekly", label: "Weekly" },
    { value: "monthly", label: "Monthly" },
    { value: "xtra-data", label: "Xtradata" },
  ],
};

export const NINE_MOBILE = {
  planTypes: [
    { value: "daily", label: "Daily" },
    { value: "weekly", label: "Weekly" },
    { value: "monthly", label: "Monthly" },
    { value: "xtra-data", label: "Xtradata" },
  ],
};
